### ISSUE TITLE
Hey guys loved the project!!!!!

### ISSUE THREAD

**Issue by saumyaborwankar** [andrlime/Wildhacks2023#17]
I think is not relevant to the project but can you guys tell me how you made the video presentation for your wild hacks submission? P.S. Im posting this here cuz I guess this is what you guys check rather than youtube comments.

**Comment by miyaliu627** [comment]
Hi Saumy!

I used premiere pro to edit. It was definitely a lot of sound design and storyboarding. The actual editing is not too difficult but just time-consuming. 

Thank you for liking the project!
Miya
